INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES (1, 'kkukkumania', '321321', 'kkukku', 'kkukku@gmail.com', CURRENT_TIMESTAMP());
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES (2, 'ssoonmania', '1', 'ssoon', 'ssoon@gmail.com', CURRENT_TIMESTAMP());

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, COUNT_OF_ANSWER) VALUES  (1, 1, '국내에서 Ruby on Rails와 Play가', 'Ruby on Rails(이하 ROR)는', CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, COUNT_OF_ANSWER) VALUES  (2, 2, 'SpringFramework', 'Spring Boot', CURRENT_TIMESTAMP(), 0);